"""Per-class object size priors, in metres.

GENERATED by ``scripts/gen_size_prior.py`` — do not edit by hand.

Median (lx, ly, lz) per label over 15 VLA-3D Unity scenes,
for labels seen at least 2 times (172 of 274 labels).

A partial LiDAR view sees one face of an object, so a measured box
under-reports its depth; the challenge scores object reference by 3D
IoU, where that is as expensive as a position error. Falling back to
the typical size of the class recovers most of it: on livingroom_3, a
prior-sized box on a perfect centre scores mean IoU 0.40 against 0.003
for our measured boxes.
"""

from __future__ import annotations

import re


SIZE_PRIOR: dict[str, tuple[float, float, float]] = {
    "air conditioner": (0.816, 0.492, 2.31),  # n=3
    "air vent": (1.055, 0.238, 0.033),  # n=4
    "balcony door": (1.254, 0.243, 3.587),  # n=4
    "bed": (2.589, 2.89, 1.165),  # n=5
    "bed bench": (2.16, 0.576, 0.397),  # n=2
    "bedroom light": (0.991, 0.987, 0.156),  # n=5
    "bedside table": (0.872, 0.795, 0.651),  # n=2
    "beer bottle": (0.088, 0.088, 0.324),  # n=4
    "bench": (1.578, 0.661, 0.466),  # n=4
    "bird decoration": (0.243, 0.069, 0.41),  # n=2
    "blanket": (1.753, 1.593, 0.415),  # n=3
    "book": (0.185, 0.179, 0.248),  # n=56
    "bookcase": (0.768, 1.547, 1.998),  # n=2
    "books": (0.748, 0.233, 0.287),  # n=12
    "boot": (0.312, 0.118, 0.282),  # n=2
    "bottle": (0.208, 0.208, 0.2),  # n=24
    "bowl": (0.259, 0.252, 0.115),  # n=12
    "box": (0.352, 0.318, 0.204),  # n=16
    "cabinet": (1.649, 0.522, 0.829),  # n=11
    "calligraphy painting": (0.509, 0.038, 0.699),  # n=3
    "candle": (0.077, 0.076, 0.115),  # n=12
    "candlestick": (0.117, 0.117, 0.242),  # n=2
    "canvas": (0.59, 0.104, 1.026),  # n=2
    "carpet": (3.246, 1.904, 0.019),  # n=18
    "ceiling": (7.98, 7.292, 0.206),  # n=19
    "ceiling lamp": (0.348, 0.347, 0.325),  # n=19
    "ceiling light": (0.145, 0.145, 0.084),  # n=84
    "chair": (0.631, 0.64, 1.037),  # n=76
    "chopsticks": (0.259, 0.053, 0.005),  # n=3
    "circular light": (0.411, 0.404, 0.106),  # n=2
    "clock": (0.307, 0.06, 0.281),  # n=10
    "coffee cup": (0.095, 0.095, 0.114),  # n=7
    "coffee machine": (0.442, 0.276, 0.376),  # n=2
    "coffee table": (1.758, 0.878, 0.55),  # n=4
    "column": (0.491, 0.494, 2.734),  # n=18
    "computer": (0.373, 0.365, 0.079),  # n=3
    "computer monitor": (0.493, 0.193, 0.491),  # n=9
    "computer mouse": (0.109, 0.065, 0.031),  # n=10
    "cooker": (0.355, 0.354, 0.378),  # n=2
    "couch": (2.114, 1.179, 1.086),  # n=5
    "cup": (0.109, 0.101, 0.085),  # n=16
    "cupboard": (1.764, 0.811, 1.606),  # n=3
    "curtain": (1.293, 0.254, 3.481),  # n=19
    "curtains": (1.097, 0.072, 3.221),  # n=2
    "deck chair": (1.402, 0.784, 0.965),  # n=2
    "decorative ball": (0.126, 0.124, 0.127),  # n=3
    "desk": (0.798, 0.889, 0.497),  # n=3
    "desk light": (0.426, 0.425, 0.656),  # n=3
    "dining chair": (0.704, 0.704, 1.224),  # n=4
    "dining table": (2.389, 1.18, 1.004),  # n=2
    "dish": (0.318, 0.316, 0.021),  # n=15
    "door": (0.801, 0.077, 2.08),  # n=55
    "door frame": (1.186, 0.15, 2.496),  # n=37
    "drawer": (0.756, 0.848, 0.267),  # n=11
    "drawers": (0.476, 0.678, 0.639),  # n=4
    "dressing chair": (0.503, 0.503, 0.626),  # n=2
    "dumbbell": (0.274, 0.274, 0.104),  # n=2
    "dvd": (0.52, 0.299, 0.063),  # n=5
    "dvd player": (0.602, 0.509, 0.153),  # n=3
    "eye glasses": (0.151, 0.144, 0.042),  # n=4
    "face cream": (0.104, 0.1, 0.055),  # n=4
    "fence": (2.634, 0.087, 1.145),  # n=2
    "file": (0.324, 0.243, 0.046),  # n=4
    "fireplace": (1.287, 0.08, 0.55),  # n=3
    "floor": (7.927, 6.682, 0.067),  # n=19
    "flower": (0.134, 0.084, 0.444),  # n=3
    "flowers": (0.275, 0.188, 0.518),  # n=5
    "focus light": (0.15, 0.15, 0.02),  # n=88
    "folder": (0.679, 0.247, 0.342),  # n=10
    "fork": (0.201, 0.024, 0.014),  # n=6
    "fossil decoration": (0.298, 0.113, 0.337),  # n=2
    "framed record": (0.673, 0.04, 0.806),  # n=3
    "gate": (0.446, 2.131, 2.665),  # n=2
    "glass": (0.078, 0.079, 0.08),  # n=9
    "glass wall": (2.52, 0.029, 2.869),  # n=2
    "handle": (0.261, 0.224, 0.039),  # n=3
    "hanger": (0.445, 0.018, 0.208),  # n=3
    "horse figurine": (0.285, 0.149, 0.275),  # n=2
    "kettle": (0.244, 0.204, 0.346),  # n=4
    "keyboard": (0.384, 0.187, 0.024),  # n=9
    "kitchen cabinet": (2.61, 5.091, 2.49),  # n=2
    "kitchen door": (1.372, 0.209, 2.932),  # n=3
    "kitchen island": (3.257, 0.733, 1.025),  # n=2
    "kitchen knife": (0.12, 0.023, 0.239),  # n=3
    "knife": (0.148, 0.022, 0.238),  # n=2
    "lamp": (0.449, 0.443, 0.924),  # n=48
    "lantern": (0.162, 0.162, 0.421),  # n=5
    "laptop": (0.408, 0.407, 0.279),  # n=2
    "light switch": (0.097, 0.016, 0.097),  # n=19
    "lipstick": (0.108, 0.048, 0.108),  # n=2
    "lotion": (0.071, 0.071, 0.256),  # n=3
    "magazine": (0.337, 0.319, 0.041),  # n=4
    "map": (0.339, 0.241, 0.027),  # n=2
    "marker": (0.143, 0.011, 0.012),  # n=8
    "mattress": (2.626, 2.24, 0.194),  # n=3
    "microwave": (0.772, 0.411, 0.549),  # n=3
    "mirror": (0.823, 0.04, 0.839),  # n=9
    "mouse pad": (0.299, 0.212, 0.004),  # n=4
    "newspaper": (0.33, 0.364, 0.049),  # n=2
    "night stand": (0.626, 0.626, 0.621),  # n=6
    "nightstand": (0.665, 0.976, 0.719),  # n=4
    "notebook": (0.197, 0.135, 0.023),  # n=2
    "oil bottle": (0.163, 0.101, 0.415),  # n=2
    "ottoman": (0.749, 1.014, 0.514),  # n=2
    "outside door": (1.596, 0.178, 2.102),  # n=2
    "painting": (0.847, 0.035, 1.06),  # n=14
    "paper": (0.186, 0.157, 0.08),  # n=11
    "paper box": (0.425, 0.283, 0.24),  # n=3
    "paper cup": (0.088, 0.088, 0.106),  # n=3
    "paper holder": (0.157, 0.157, 0.22),  # n=2
    "pen": (0.146, 0.015, 0.011),  # n=3
    "phone": (0.219, 0.168, 0.06),  # n=10
    "photo": (0.173, 0.143, 0.28),  # n=9
    "picture": (0.532, 0.018, 0.603),  # n=39
    "pillow": (0.442, 0.408, 0.363),  # n=92
    "placemat": (0.401, 0.261, 0.004),  # n=2
    "plate": (0.151, 0.147, 0.011),  # n=7
    "poster": (0.34, 0.008, 0.29),  # n=5
    "potted bamboo": (0.279, 0.173, 1.79),  # n=2
    "potted cactus": (0.098, 0.098, 0.188),  # n=3
    "potted plant": (0.73, 0.642, 1.008),  # n=57
    "quilt": (2.544, 1.691, 0.589),  # n=4
    "range hood": (0.73, 0.628, 1.655),  # n=3
    "round table": (0.684, 0.684, 0.32),  # n=2
    "sculpture": (0.374, 0.189, 0.573),  # n=3
    "shelf": (1.436, 0.538, 0.618),  # n=7
    "shower": (2.046, 1.47, 3.02),  # n=3
    "shower head": (0.314, 0.621, 1.397),  # n=2
    "shower tap": (0.344, 0.422, 1.215),  # n=2
    "side table": (0.835, 0.699, 0.611),  # n=2
    "sink": (0.942, 0.572, 0.428),  # n=6
    "sink cabinet": (0.514, 1.272, 0.941),  # n=2
    "sliced bread": (0.228, 0.145, 0.04),  # n=2
    "slipper": (0.42, 0.356, 0.067),  # n=3
    "soap": (0.114, 0.114, 0.119),  # n=2
    "sofa": (2.129, 1.006, 0.859),  # n=19
    "sofa cushion": (1.061, 0.363, 0.519),  # n=4
    "speaker": (0.226, 0.202, 0.56),  # n=12
    "spice jar": (0.073, 0.077, 0.185),  # n=9
    "spoon": (0.145, 0.028, 0.013),  # n=11
    "spot light": (0.158, 0.15, 0.022),  # n=6
    "sticky notes": (0.085, 0.011, 0.081),  # n=2
    "stool": (0.388, 0.388, 0.845),  # n=8
    "stove": (1.119, 0.587, 0.053),  # n=2
    "sushi": (0.052, 0.051, 0.027),  # n=3
    "symbol decoraion": (0.214, 0.016, 0.498),  # n=2
    "table": (1.105, 0.674, 0.542),  # n=26
    "tablecloth": (1.528, 0.392, 0.138),  # n=2
    "tap": (0.205, 0.055, 0.171),  # n=2
    "toilet": (0.717, 0.635, 1.064),  # n=4
    "toilet paper": (0.194, 0.119, 0.148),  # n=4
    "towel": (0.408, 0.137, 0.493),  # n=8
    "towel rack": (0.557, 0.273, 0.994),  # n=3
    "trash bin": (0.389, 0.388, 0.413),  # n=3
    "trash can": (0.326, 0.322, 0.397),  # n=6
    "tray": (0.449, 0.483, 0.014),  # n=4
    "tree": (7.674, 6.387, 7.302),  # n=20
    "tv": (1.243, 0.06, 0.791),  # n=13
    "tv cabinet": (2.801, 0.604, 0.68),  # n=7
    "tv remote": (0.204, 0.051, 0.019),  # n=6
    "tv stand": (3.85, 0.739, 0.452),  # n=2
    "vase": (0.217, 0.191, 0.347),  # n=32
    "wall": (6.735, 0.133, 2.88),  # n=79
    "wall lamp": (0.193, 0.101, 0.446),  # n=6
    "wardrobe": (2.523, 0.642, 3.001),  # n=5
    "wardrobe door": (1.355, 0.049, 2.217),  # n=2
    "water bottle": (0.088, 0.087, 0.261),  # n=2
    "window": (0.998, 0.06, 1.276),  # n=40
    "window frame": (1.112, 0.184, 1.721),  # n=10
    "windows": (2.071, 1.642, 2.07),  # n=3
    "wine bottle": (0.465, 0.119, 0.128),  # n=19
    "wine glass": (0.082, 0.081, 0.223),  # n=4
}


def size_for(label: str) -> tuple[float, float, float] | None:
    """Typical (lx, ly, lz) for ``label``, or ``None`` if unknown."""
    return SIZE_PRIOR.get(re.sub(r"[_\s]+", " ", label.strip().lower()))
