"""Open-vocabulary class list management for the perception responder.

YOLOv8x-World v2 accepts a different class list per call — but
re-encoding the prompt embeddings takes ~50 ms on a 4090 for ~50
classes. We keep a stable hybrid list:

* A small **prior** of common indoor objects so the scene graph
  accumulates labels between questions (object referenced *next*
  tick).
* **Question-derived nouns** merged on top, so the detector sees the
  task-specific vocabulary too.

The class list is **dedup-stable** so the sidecar's prompt embedding
cache stays warm: the same set of classes always produces the same
ordered tuple, and the responder only calls ``/reload_classes`` when
the set actually changes.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Iterable

log = logging.getLogger(__name__)

# Open-vocabulary class prior — GENERATED by scripts/gen_vocab_prior.py.
#
# Labels appearing in at least 2 of the 15 VLA-3D Unity
# scenes, ranked by cross-scene generality then frequency and capped at
# 100 (100 labels, covering 81% of all ground-truth
# objects across every scene). The detector can ONLY emit labels from this
# list, and its runtime grows with the count, so the cap trades the rarest
# scene-specific labels for a bounded prompt. Recurring across scenes is the
# evidence that matters: the challenge scenes are unseen, so a label that
# appears many times in ONE scene is not thereby general.
#
# Generated from the scene vocabulary rather than written by hand so the
# detector uses the same words as the ground truth and the questions —
# calling a couch a "sofa" is a miss even when the detection is perfect.
DEFAULT_PRIOR: tuple[str, ...] = (
    "balcony door",
    "bed",
    "bedroom light",
    "beer bottle",
    "bench",
    "bird decoration",
    "blanket",
    "book",
    "bookcase",
    "bottle",
    "bowl",
    "box",
    "cabinet",
    "candle",
    "carpet",
    "ceiling",
    "ceiling lamp",
    "ceiling light",
    "chair",
    "chopsticks",
    "clock",
    "coffee cup",
    "coffee machine",
    "coffee table",
    "column",
    "computer monitor",
    "computer mouse",
    "couch",
    "cup",
    "curtain",
    "dining table",
    "dish",
    "door",
    "door frame",
    "drawer",
    "dvd",
    "eye glasses",
    "file",
    "fireplace",
    "floor",
    "flowers",
    "focus light",
    "folder",
    "glass",
    "handle",
    "hanger",
    "horse figurine",
    "kettle",
    "keyboard",
    "kitchen cabinet",
    "kitchen island",
    "lamp",
    "lantern",
    "laptop",
    "light switch",
    "magazine",
    "marker",
    "mattress",
    "microwave",
    "mirror",
    "newspaper",
    "night stand",
    "ottoman",
    "painting",
    "paper",
    "paper holder",
    "pen",
    "phone",
    "photo",
    "picture",
    "pillow",
    "potted plant",
    "quilt",
    "range hood",
    "sculpture",
    "shelf",
    "shower",
    "sink",
    "slipper",
    "sofa",
    "speaker",
    "stool",
    "table",
    "toilet",
    "toilet paper",
    "towel",
    "towel rack",
    "trash bin",
    "trash can",
    "tray",
    "tv",
    "tv cabinet",
    "tv remote",
    "vase",
    "wall",
    "wall lamp",
    "wardrobe",
    "window",
    "window frame",
    "wine bottle",
)

# Architecture, not objects. These get detected (a counting question may well
# ask about doors or windows) but they are *stuff*, not instances: one mask
# covers a whole surface, often spanning several rooms, so lifting it produces
# a point cloud metres across and fusing those across frames yields dozens of
# overlapping "objects" that are all the same floor.
#
# Measured on the livingroom_3 corpus: these labels are 40% of all lifted
# observations, their single-frame point clouds span 2.0 m at the median
# (vs 1.35 m for real objects), and they accounted for 111 of 259 fused
# nodes — floor alone came out as 68 separate objects against 1 in ground
# truth. Tagging them keeps the detections available for counting while
# keeping them out of the instance list an LLM reasons over.
STRUCTURE_LABELS: frozenset[str] = frozenset({
    "wall", "walls", "exterior walls", "interior wall", "partition wall",
    "floor", "ceiling", "carpet", "rug",
    "door", "door frame", "doorframe", "window", "window frame",
    "glass", "column", "stairs", "staircase", "railing",
})


def is_structure(label: str) -> bool:
    """True for architecture/`stuff` labels that must not become instances.

    Underscores collapse to spaces as well as whitespace, matching how the
    responder compares labels (``_norm_label``) — a scene graph written as
    ``door_frame`` has to hit the same verdict as ``door frame``.
    """
    return re.sub(r"[_\s]+", " ", label.strip().lower()) in STRUCTURE_LABELS


# Words to drop from a question before treating the rest as candidate
# noun labels. Kept conservative — YOLO-World ignores junk classes
# anyway (they just get low scores), so over-removing is fine but
# under-removing rarely hurts.
_STOPWORDS: frozenset[str] = frozenset({
    "the", "a", "an", "is", "are", "was", "were", "be", "been", "being",
    "of", "in", "on", "at", "to", "from", "for", "with", "by", "and", "or",
    "this", "that", "these", "those", "it", "its", "there", "here",
    "you", "your", "yours", "i", "my", "mine", "we", "our", "ours",
    "how", "what", "which", "where", "when", "who", "whose", "why",
    "many", "much", "some", "any", "more", "most", "less", "least",
    "can", "could", "would", "should", "do", "does", "did", "have",
    "has", "had", "find", "go", "show", "tell", "near", "next",
    "between", "above", "below", "behind", "front", "left", "right",
})


class Vocabulary:
    """Hybrid scene-prior + question-derived class list.

    ``current_classes(question)`` is the only method callers need —
    it returns a stable, deduplicated tuple that the
    :class:`HTTPPerceptionClient` can compare against the last list it
    pushed to the sidecar.
    """

    def __init__(
        self,
        prior: Iterable[str] = DEFAULT_PRIOR,
        *,
        stopwords: frozenset[str] = _STOPWORDS,
        dynamic: set[str] | None = None,
    ) -> None:
        self._prior: tuple[str, ...] = tuple(_normalise(p) for p in prior)
        self._stopwords = stopwords
        # Shared, mutable set of extra class phrases contributed at runtime by
        # the VLM (objects it sees in the panorama + synonyms), so rare objects
        # a fixed prior misses — e.g. "hookah"/"shisha" — get into the
        # open-vocab detector's prompt. Written by the navigator, read here.
        self._dynamic = dynamic if dynamic is not None else set()

    @property
    def prior(self) -> tuple[str, ...]:
        return self._prior

    def current_classes(self, question_text: str | None) -> tuple[str, ...]:
        """Return the (prior ∪ question-derived ∪ VLM-observed) class list for
        the current tick. Order: prior first, then question nouns, then the
        VLM's dynamic observations, deduped.
        """
        seen: dict[str, None] = {label: None for label in self._prior}
        if question_text:
            for label in self._extract_nouns(question_text):
                if label not in seen:
                    seen[label] = None
        for phrase in sorted(self._dynamic):
            label = _normalise(phrase)
            if label and label not in seen:
                seen[label] = None
        return tuple(seen.keys())

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _extract_nouns(self, text: str) -> list[str]:
        """Pull plausible object labels out of a question.

        v1 heuristic: lowercase, strip punctuation, drop stopwords,
        strip trailing plural ``s`` (so ``"chairs"`` becomes
        ``"chair"`` and matches the prior). Multi-word concepts can be
        added by the caller via ``Vocabulary(prior=...)``; the
        extractor itself emits single words only.
        """
        words = re.findall(r"[a-z]+", text.lower())
        out: list[str] = []
        for w in words:
            if w in self._stopwords or len(w) < 2:
                continue
            singular = _depluralise(w)
            if singular not in out:
                out.append(singular)
        return out


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _normalise(label: str) -> str:
    """Lower-case and collapse whitespace. Keeps internal hyphens."""
    return re.sub(r"\s+", " ", label.strip().lower())


def _depluralise(word: str) -> str:
    """Strip a trailing ``s``/``es`` when the result is still ≥3 chars.

    Conservative on purpose — we only handle the common case
    (``chairs`` → ``chair``, ``boxes`` → ``boxe`` is undesirable so we
    leave words ending in -ses/-xes/-zes/-shes/-ches alone). YOLO-World
    forgives the rest.
    """
    if len(word) < 4:
        return word
    if word.endswith(("ses", "xes", "zes", "shes", "ches")):
        return word
    if word.endswith("s"):
        return word[:-1]
    return word
