# --- A/B pairs: same question, both arms back to back ---
# Ordered most-likely-to-fail first, so a truncated run still carries signal.
AB_Q=(); AB_S=(); AB_T=()
AB_S+=("arabic_room"); AB_T+=("arabicq5"); AB_Q+=("First, go to the potted plant furthest from the hookah, then take the path between the two columns, and stop at the tray on the table.")
AB_S+=("livingroom_1"); AB_T+=("livingq5"); AB_Q+=("First, go near the lamp closest to the black chair, then take the path between the sofa and the round tables, and stop at the cabinet with a picture above it.")
AB_S+=("office_2"); AB_T+=("officeq4"); AB_Q+=("Go near the potted plant on the cabinet and stop at the window closest to the clock.")
AB_S+=("home_building_1"); AB_T+=("home_bq5"); AB_Q+=("First, go to the nightstand with a clock on it, then take the path between the dining table and the picture, and stop at the trash can closest to the refridgerator.")
AB_S+=("loft"); AB_T+=("loftq5"); AB_Q+=("Go near the fireplace, pass by the stairs, then stop at the sphere decoration on the cabinet.")

# --- coverage: every instruction question on an unpacked scene ---
CV_Q=(); CV_S=(); CV_T=()
CV_S+=("arabic_room"); CV_T+=("arabicq4"); CV_Q+=("Go near the stool under the picture and stop at the small table farthest from the columns.")
CV_S+=("arabic_room"); CV_T+=("arabicq5"); CV_Q+=("First, go to the potted plant furthest from the hookah, then take the path between the two columns, and stop at the tray on the table.")
CV_S+=("chinese_room"); CV_T+=("chinesq4"); CV_Q+=("Go near the potted plant on the table and stop at the painting near the TV.")
CV_S+=("chinese_room"); CV_T+=("chinesq5"); CV_Q+=("First, go near the tea table with the elephant figurine on it, then stop at the table with the horse figurine on it, avoiding the path between the chair and the folding screen.")
CV_S+=("home_building_1"); CV_T+=("home_bq4"); CV_Q+=("Go to the coffee table with the kettle on it and stop at the dining table near the big picture.")
CV_S+=("home_building_1"); CV_T+=("home_bq5"); CV_Q+=("First, go to the nightstand with a clock on it, then take the path between the dining table and the picture, and stop at the trash can closest to the refridgerator.")
CV_S+=("home_building_2"); CV_T+=("home_bq4"); CV_Q+=("Go near the magazine on the ottoman, then go to the potted plant on the dressing table.")
CV_S+=("home_building_2"); CV_T+=("home_bq5"); CV_Q+=("Take the path between the sofa and the coffee table and go to the kettle on the dining table, then go to the potted plant between the curtain and the TV.")
CV_S+=("hotel_room_2"); CV_T+=("hotel_q4"); CV_Q+=("Go between the bench and the bed and stop at the lamp closest to the fireplace.")
CV_S+=("hotel_room_2"); CV_T+=("hotel_q5"); CV_Q+=("First, go to the picture closest to the door, then take the path between the TV cabinet and the bed, and stop by the curtain closest to the TV.")
CV_S+=("japanese_room"); CV_T+=("japaneq4"); CV_Q+=("Go near the small table with a vase on it and then to the flowers near the jar.")
CV_S+=("japanese_room"); CV_T+=("japaneq5"); CV_Q+=("Go to the lantern closest to the fan decoration, then take the path near the wardrobe doors to the flowers on the display ledge.")
CV_S+=("livingroom_1"); CV_T+=("livingq4"); CV_Q+=("Go to the potted plant closest to the pyramid candle holder and stop at the vase between the TV and the door.")
CV_S+=("livingroom_1"); CV_T+=("livingq5"); CV_Q+=("First, go near the lamp closest to the black chair, then take the path between the sofa and the round tables, and stop at the cabinet with a picture above it.")
CV_S+=("livingroom_2"); CV_T+=("livingq4"); CV_Q+=("Go to the microwave on the kitchen counter and then go to the crystal ball decoration on the shelf near the TV.")
CV_S+=("livingroom_2"); CV_T+=("livingq5"); CV_Q+=("First, go to the chair near the window, then stop at the soccer ball near the couch, avoiding the path between the TV and the tea table.")
CV_S+=("livingroom_3"); CV_T+=("livingq4"); CV_Q+=("Take the path near the TV and go to the pillow farthest from the lamp.")
CV_S+=("livingroom_3"); CV_T+=("livingq5"); CV_Q+=("First, go near the stool, then take the path near the cabinet, and stop at the bowl on the table.")
CV_S+=("loft"); CV_T+=("loftq4"); CV_Q+=("Go to the cup near the TV remote and avoid the path near the cabinet.")
CV_S+=("loft"); CV_T+=("loftq5"); CV_Q+=("Go near the fireplace, pass by the stairs, then stop at the sphere decoration on the cabinet.")
CV_S+=("office_1"); CV_T+=("officeq4"); CV_Q+=("Go to the potted plant furthest from the projector screen then stop at the water cooler near the window.")
CV_S+=("office_1"); CV_T+=("officeq5"); CV_Q+=("First, go near the potted plant on the shelf, then take the path between the two tables, and stop at the bench closest to the map wall decal.")
CV_S+=("office_2"); CV_T+=("officeq4"); CV_Q+=("Go near the potted plant on the cabinet and stop at the window closest to the clock.")
CV_S+=("office_2"); CV_T+=("officeq5"); CV_Q+=("First, go to the trash can near the cabinet, then go to the folder on the cabinet closest to the whiteboard, and finally, to the door near the exit sign.")
CV_S+=("studio"); CV_T+=("studioq4"); CV_Q+=("Go to the vases on the cabinet below the TV and stop at the guitar near the couch.")
CV_S+=("studio"); CV_T+=("studioq5"); CV_Q+=("First, go to the vase closest to the easel, then, take the path between the couch and the table and stop at the window closest to the couch.")
