"""Regenerate the detector's class prior from the VLA-3D scene vocabulary.

Two problems with hand-writing this list, both of which cost us recall:

1. **Coverage.** The previous prior was copied from `arabic_room`'s
   `object_list.txt`, so it carried `hookah` and `arabic jar` but not `chair`.
   Measured against ground truth, 46 of 108 objects in `livingroom_3` and 373
   of 432 in `home_building_1` had labels the detector was never prompted for
   — and an open-vocabulary detector cannot find what it is not asked for.

2. **Wording.** YOLO-World's natural word for a thing is not always VLA-3D's.
   We detected the `livingroom_3` sofa correctly and called it "sofa"; ground
   truth calls it "couch", so it scored as a miss *and* would not match a
   question asking about a couch. Generating the prior from the scene
   vocabulary makes the detector speak the same language as the questions.

Selection rule: a label must appear in at least ``--min-scenes`` distinct
scenes. Frequency within one scene is not evidence of generality — the test
scenes are unseen, so what matters is whether a label recurs across scenes.

Run from the repo root (needs the VLA-3D Unity dump, which is not committed)::

    python scripts/gen_vocab_prior.py

It rewrites the DEFAULT_PRIOR block in
``src/xiao_hei_vln/perception/vocab.py`` in place; pass ``--print`` to inspect
the list instead.
"""

from __future__ import annotations

import argparse
import collections
import re
import sys
from pathlib import Path

DEFAULT_DIR = Path("dataset_generator/vla-3d/Unity")
VOCAB_PY = Path("src/xiao_hei_vln/perception/vocab.py")
MIN_SCENES = 2

# Labels that name a *scene*, not an object we could detect and point at.
_DROP = {"unknown"}


def collect(root: Path) -> tuple[dict[str, set[str]], collections.Counter]:
    scenes: dict[str, set[str]] = collections.defaultdict(set)
    counts: collections.Counter = collections.Counter()
    for path in sorted(root.glob("*/object_list.txt")):
        scene = path.parent.name
        for line in path.read_text().splitlines():
            line = line.strip()
            if not line or '"' not in line:
                continue
            label = line[line.index('"') + 1:].strip('"').strip().lower()
            label = re.sub(r"\s+", " ", label)
            if not label or label in _DROP:
                continue
            scenes[label].add(scene)
            counts[label] += 1
    return scenes, counts


def _collapse_plurals(labels: list[str], counts: collections.Counter) -> list[str]:
    """Drop a plural whose singular is also present.

    VLA-3D annotators wrote both "book" and "books", "window" and "windows".
    Prompting the detector with both spellings just buys two overlapping
    detections of the same object, which then have to be un-duplicated
    downstream. Keep whichever form the annotators used more often.
    """
    have = set(labels)
    out = []
    for label in labels:
        if label.endswith("s"):
            singular = label[:-1]
            if singular in have and counts[singular] >= counts[label]:
                continue
        elif label + "s" in have and counts[label + "s"] > counts[label]:
            continue
        out.append(label)
    return out


def render_block(labels: list[str], n_scenes: int, min_scenes: int,
                 coverage: float) -> str:
    lines = [
        "# Open-vocabulary class prior — GENERATED by scripts/gen_vocab_prior.py.",
        "#",
        f"# Every label that appears in at least {min_scenes} of the {n_scenes} VLA-3D",
        f"# Unity scenes ({len(labels)} labels, covering {coverage:.0%} of all ground-truth",
        "# objects). Recurring across scenes is the evidence that matters here: the",
        "# challenge scenes are unseen, so a label that appears many times in one",
        "# scene is not thereby general.",
        "#",
        "# Generated from the scene vocabulary rather than written by hand so the",
        "# detector uses the same words as the ground truth and the questions —",
        '# calling a couch a "sofa" is a miss even when the detection is perfect.',
        "DEFAULT_PRIOR: tuple[str, ...] = (",
    ]
    lines += [f'    "{label}",' for label in labels]
    lines.append(")")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--vla3d-dir", type=Path, default=DEFAULT_DIR)
    ap.add_argument("--min-scenes", type=int, default=MIN_SCENES)
    ap.add_argument("--vocab-py", type=Path, default=VOCAB_PY)
    ap.add_argument("--print", action="store_true", help="print instead of rewriting")
    args = ap.parse_args(argv)

    if not args.vla3d_dir.is_dir():
        print(f"error: {args.vla3d_dir} not found", file=sys.stderr)
        return 2

    scenes, counts = collect(args.vla3d_dir)
    n_scenes = len({s for v in scenes.values() for s in v})
    labels = sorted(l for l, s in scenes.items() if len(s) >= args.min_scenes)
    labels = _collapse_plurals(labels, counts)
    coverage = sum(counts[l] for l in labels) / max(sum(counts.values()), 1)
    block = render_block(labels, n_scenes, args.min_scenes, coverage)

    if args.print:
        print(block)
        return 0

    text = args.vocab_py.read_text()
    pattern = re.compile(
        r"(?:^#[^\n]*\n)*^DEFAULT_PRIOR: tuple\[str, \.\.\.\] = \([^)]*\)",
        re.MULTILINE,
    )
    if not pattern.search(text):
        print("error: DEFAULT_PRIOR block not found in "
              f"{args.vocab_py}", file=sys.stderr)
        return 1
    args.vocab_py.write_text(pattern.sub(lambda _: block, text, count=1))
    print(f"{args.vocab_py}: DEFAULT_PRIOR now has {len(labels)} labels "
          f"({coverage:.0%} GT coverage, min_scenes={args.min_scenes})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
