"""Regenerate ``xiao_hei_vln.perception.size_prior`` from the VLA-3D scenes.

Our lifted boxes come from LiDAR returns on the *visible* surface of an
object, so they systematically under- or over-shoot its true extent. The
challenge scores object-reference answers by 3D IoU, where size error is as
costly as position error — and a per-class median size measured over every
scene we have is a far better estimate than anything a single partial scan
supports.

Run from the repo root (needs the VLA-3D Unity dump, which is not committed)::

    python scripts/gen_size_prior.py > src/xiao_hei_vln/perception/size_prior.py

The output is a plain constant table so nothing at runtime depends on
``dataset_generator/`` being present.
"""

from __future__ import annotations

import argparse
import collections
import statistics as st
import sys
from pathlib import Path

DEFAULT_DIR = Path("dataset_generator/vla-3d/Unity")
MIN_SAMPLES = 2          # a single instance is an anecdote, not a prior


def read_object_list(path: Path) -> list[tuple[str, tuple[float, float, float]]]:
    """``object_list.txt`` → [(label, (lx, ly, lz)), ...]."""
    out = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or '"' not in line:
            continue
        q = line.index('"')
        label = line[q + 1:].strip('"').strip().lower()
        fields = line[:q].split()
        if len(fields) < 7:
            continue
        try:
            size = (float(fields[4]), float(fields[5]), float(fields[6]))
        except ValueError:
            continue
        out.append((label, size))
    return out


def collect(root: Path) -> dict[str, list[tuple[float, float, float]]]:
    sizes: dict[str, list] = collections.defaultdict(list)
    for path in sorted(root.glob("*/object_list.txt")):
        for label, size in read_object_list(path):
            if label and label != "unknown":
                sizes[label].append(size)
    return sizes


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--vla3d-dir", type=Path, default=DEFAULT_DIR)
    ap.add_argument("--min-samples", type=int, default=MIN_SAMPLES)
    args = ap.parse_args(argv)

    if not args.vla3d_dir.is_dir():
        print(f"error: {args.vla3d_dir} not found", file=sys.stderr)
        return 2

    sizes = collect(args.vla3d_dir)
    n_scenes = len(list(args.vla3d_dir.glob("*/object_list.txt")))
    table = {
        label: tuple(round(st.median(s[i] for s in samples), 3) for i in range(3))
        for label, samples in sorted(sizes.items())
        if len(samples) >= args.min_samples
    }
    counts = {label: len(samples) for label, samples in sizes.items()}

    print('"""Per-class object size priors, in metres.')
    print()
    print("GENERATED by ``scripts/gen_size_prior.py`` — do not edit by hand.")
    print()
    print(f"Median (lx, ly, lz) per label over {n_scenes} VLA-3D Unity scenes,")
    print(f"for labels seen at least {args.min_samples} times "
          f"({len(table)} of {len(sizes)} labels).")
    print()
    print("A partial LiDAR view sees one face of an object, so a measured box")
    print("under-reports its depth; the challenge scores object reference by 3D")
    print("IoU, where that is as expensive as a position error. Falling back to")
    print("the typical size of the class recovers most of it: on livingroom_3, a")
    print("prior-sized box on a perfect centre scores mean IoU 0.40 against 0.003")
    print("for our measured boxes.")
    print('"""')
    print()
    print("from __future__ import annotations")
    print()
    print("import re")
    print()
    print()
    print("SIZE_PRIOR: dict[str, tuple[float, float, float]] = {")
    for label, size in table.items():
        print(f'    "{label}": {size},'
              f'  # n={counts[label]}')
    print("}")
    print()
    print()
    print("def size_for(label: str) -> tuple[float, float, float] | None:")
    print('    """Typical (lx, ly, lz) for ``label``, or ``None`` if unknown."""')
    print('    return SIZE_PRIOR.get(re.sub(r"[_\\s]+", " ", label.strip().lower()))')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
